<?php
/**
 * @file
 * Code for the Commerce Marketplace Blog feature.
 */

include_once 'ogmk_blog.features.inc';

/**
 * Hooks.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ogmk_blog_form_ogmk_post_node_form_alter(&$form, &$form_state, $form_id) {
  // If the user cannot post globally (e.g. not without defining a shop
  // context), we mark the ogmk_shops_ref field as required.
  $can_post_globally = user_access('create ogmk_post content');

  if (!$can_post_globally) {
    $language = $form['ogmk_shops_ref']['#language'];
    $form['ogmk_shops_ref'][$language][0]['#required'] = TRUE;

    // If there is only 1 shop that the user can post to, there's no point in
    // displaying the field. Pre-select the only option and deny access to the
    // field.
    $shop_options = &$form['ogmk_shops_ref'][$language][0]['default']['#options'];

    // 1 Shop + the 'None' option = 2 options.
    if (count($shop_options) == 2) {
      unset($shop_options['_none']);
      $form['ogmk_shops_ref'][$language][0]['default']['#default_value'] = key($shop_options);
      $form['ogmk_shops_ref']['#access'] = FALSE;
    }
  }

  // Add a Cancel button.
  $form['actions']['cancel'] = array(
    '#type' => 'button',
    '#access' => TRUE,
    '#value' => t('Cancel'),
    '#attributes' => array('onClick' => 'history.go(-1);return true;'),
    '#weight' => 6,
  );
}
